language: node_js
node_js:
- '8'
env:
- GIT_DEPLOY_DIR: dist
script: npm run build
after_success:
- git remote set-url origin git@github.com:ultimate-comparisons/ultimate-comparison-BASE.git
- openssl aes-256-cbc -K $encrypted_e7cc94ff2647_key -iv $encrypted_e7cc94ff2647_iv -in ./lib/travis/github_deploy_key.enc -out id_rsa -d
- ssh-add github_deploy_key
- eval "$(ssh-agent -s)"
- chmod 600 id_rsa
- ssh-add id_rsa
- git reset --hard
- echo $TRAVIS_BRANCH
- echo $TRAVIS_PULL_REQUEST
- ./lib/travis/deploy.sh
sudo: required
dist: trusty
