citations:
  - index: 0
    key: 'Adi:2004:ASM:988145.988150'
    text: >-
      Adi, A. and Etzion, O. 2004. Amit – the Situation Manager. The VLDB
      Journal 13, 2, 177–203.
  - index: 1
    key: Bry07towardsformal
    text: >-
      Bry, F. 2007. Towards formal foundations of event queries and rules. In
      Proc. Int. Workshop on Event-Driven Architecture, Processing and Systems.
  - index: 2
    key: 'Dayal:1988:ROT:60295.60304'
    text: >-
      Dayal, U., Buchmann, A.P., and McCarthy, D.R. 1988. Rules Are Objects Too:
      A Knowledge Model for an Active, Object-oriented Databasesystem. Lecture
      Notes in Computer Science on Advances in Object-oriented Database Systems,
      Springer-Verlag New York, Inc., 129–143.
  - index: 3
    key: eckertThesisCEP
    text: >-
      Eckert, M. 2008. Complex Event Processing with XChange EQ : Language
      Design, Formal Semantics, and Incremental Evaluation for Querying Events.
  - index: 5
    key: esper-reference
    text: >-
      Team, E. Esper Reference documentation.
      http://www.espertech.com/esper/release-5.1.0/esper-reference/pdf/esper_reference.pdf.
criteria:
  - NumberColumn:
      type: LABEL
      values:
        '100':
          color: '#0d0d0d'
          backgroundColor: 'hsl(75, 100%, 70%)'
        '233':
          color: '#0d0d0d'
          backgroundColor: 'hsl(105, 100%, 70%)'
